api_platform:
  title: Green Goodies
  description: API pour le projet 13
  version: 1.0.0
  formats:
    json: [ 'application/json' ]
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
